data_dir: "data/filtered_gene_bc_matrices/hg19"

scripts:
  setup: "scripts/setup_and_initialization.R"
  qc: "scripts/qc_and_preprocessing.R"
  normalization: "scripts/normalization_and_feature_selection.R"
  scaling: "scripts/scaling_and_pca.R"
  clustering: "scripts/clustering_and_umap.R"
  markers: "scripts/differential_markers_and_visualization.R"

outputs:
  initial: "results/pbmc_initial.rds"
  preprocessed: "results/pbmc_preprocessed.rds"
  normalized: "results/pbmc_normalized.rds"
  pca: "results/pbmc_pca.rds"
  umap: "results/pbmc_umap.rds"
  cluster_markers: "results/cluster_markers.rds"
  umap_plot: "results/pbmc3k_umap.png"
  umap_plot_id: "results/pbmc3k_umap_id.png"
