configfile: "config.yaml"

rule all:
    input:
        config["outputs"]["cluster_markers"],
        config["outputs"]["feature_scatter_plot"],
        config["outputs"]["variable_features_plot"],
        config["outputs"]["elbow_plot"],
        config["outputs"]["umap_dimplot_id"]

rule setup_and_initialization:
    input:
        data_dir=config["data_dir"]
    output:
        temp(config["outputs"]["initial"])
    params:
        script=config["scripts"]["setup"]
    shell:
        """
        Rscript {params.script} {input.data_dir} {output}
        """

rule qc_preprocessing:
    input:
        config["outputs"]["initial"]
    output:
        temp(config["outputs"]["preprocessed"])
    params:
        script=config["scripts"]["qc_preprocessing"]
    shell:
        """
        Rscript {params.script} {input} {output}
        """

rule qc_visualization:
    input:
        config["outputs"]["preprocessed"]
    output:
        violin=config["outputs"]["qc_violin_plot"],
        scatter=config["outputs"]["feature_scatter_plot"]
    params:
        script=config["scripts"]["qc_visualization"]
    shell:
        """
        Rscript {params.script} {input} {output.violin} {output.scatter}
        """

rule normalization_and_feature_selection:
    input:
        config["outputs"]["preprocessed"]
    output:
        temp(config["outputs"]["normalized"])
    params:
        script=config["scripts"]["normalization"]
    shell:
        """
        Rscript {params.script} {input} {output}
        """

rule variable_features_visualization:
    input:
        config["outputs"]["normalized"]
    output:
        config["outputs"]["variable_features_plot"]
    params:
        script=config["scripts"]["variable_features_visualization"]
    shell:
        """
        Rscript {params.script} {input} {output}
        """

rule scaling_and_pca:
    input:
        config["outputs"]["normalized"]
    output:
        temp(config["outputs"]["pca"])
    params:
        script=config["scripts"]["scaling"]
    shell:
        """
        Rscript {params.script} {input} {output}
        """

rule pca_visualization:
    input:
        config["outputs"]["pca"]
    output:
        pca_loadings=config["outputs"]["pca_loadings"],
        pca_dimplot=config["outputs"]["pca_dimplot"],
        pca_heatmap1=config["outputs"]["pca_heatmap1"],
        pca_heatmap15=config["outputs"]["pca_heatmap15"],
        elbow_plot=config["outputs"]["elbow_plot"]
    params:
        script=config["scripts"]["pca_visualization"]
    shell:
        """
        Rscript {params.script} {input} {output.pca_loadings} {output.pca_dimplot} {output.pca_heatmap1} {output.pca_heatmap15} {output.elbow_plot}
        """

rule clustering_and_umap:
    input:
        config["outputs"]["pca"]
    output:
        temp(config["outputs"]["umap"])
    params:
        script=config["scripts"]["clustering"]
    shell:
        """
        Rscript {params.script} {input} {output}
        """

rule differential_markers_and_visualization:
    input:
        config["outputs"]["umap"]
    output:
        markers=config["outputs"]["cluster_markers"],
        plot=config["outputs"]["umap_dimplot_id"]
    params:
        script=config["scripts"]["markers"]
    shell:
        """
        Rscript {params.script} {input} {output.markers} {output.plot}
        """
